version: 2.1

jobs:
  build-client:
    docker:
      - image: alexfalkowski/go:2.17
      - image: localstack/localstack:4.3
        environment:
          SERVICES: s3
    working_directory: ~/sashactl
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: dockerize -wait tcp://localhost:4566 -timeout 1m
      - restore_cache:
          name: restore go deps
          keys:
            - sashactl-go-cache-{{ checksum "go.sum" }}
            - sashactl-go-cache-
      - restore_cache:
          name: restore ruby deps
          keys:
            - sashactl-ruby-cache-{{ checksum "test/Gemfile.lock" }}
            - sashactl-ruby-cache-
      - run: make clean
      - run: make dep
      - save_cache:
          name: save go deps
          key: sashactl-go-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - save_cache:
          name: save ruby deps
          key: sashactl-ruby-cache-{{ checksum "test/Gemfile.lock" }}
          paths:
            - test/vendor
      - restore_cache:
          name: restore go build cache
          keys:
            - sashactl-go-build-cache-{{ checksum "go.sum" }}
            - sashactl-go-build-cache-
      - run: make clean
      - run: make lint
      - run: make sec
      - run: make features
      - run: make build analyse
      - save_cache:
          name: save go build cache
          key: sashactl-go-build-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.cache/go-build
      - run: make coverage
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: large
  build-docker:
    docker:
      - image: alexfalkowski/go:2.17
    working_directory: ~/sashactl
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build-docker
      - run: make trivy
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.19
    working_directory: ~/sashactl
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - run: release
      - run: goreleaser release
    resource_class: large
  push-docker:
    docker:
      - image: alexfalkowski/go:2.17
    working_directory: ~/sashactl
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make push-docker
    resource_class: large

workflows:
  sashactl:
    jobs:
      - build-client
      - build-docker:
          context: gh
      - release:
          serial-group: release
          context: gh
          requires:
            - build-client
            - build-docker
          filters:
            branches:
              only: master
      - push-docker:
          serial-group: push-docker
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
